# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='loser_matches', to='knights.Knight'),
            preserve_default=False,
        ),
    ]
